name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
    - TEST_ENV: hello
    steps:
    - uses: actions/checkout@v2

    - name: Read an env var
      run: echo "TEST_ENV is ${TEST_ENV}"
