name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    outputs:
      static_output_one: "value-from-one"
      from_step_one: ${{ steps.step1.outputs.result }}
    env:
      TEST_ENV: hello
    steps:
    - uses: actions/checkout@v2
    - id: step1
      name: Read an env var
      run: |
        echo "TEST_ENV is ${TEST_ENV}"
        echo "::set-output name=result::${TEST_ENV}"

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    env:
      JOB_ONE_DATA: ${{needs.job_one.outputs.from_step_one}}
    steps:
    - uses: actions/checkout@v2
    - name: Read values from job_one
      run: |
        echo "=> static_output_one: ${{needs.job_one.outputs.static_output_one}}"
        echo "=> from_step_one: ${{needs.job_one.outputs.from_step_one}}"
    - name: "Can it be used to set env vars on the job?"
      run: |
        echo "JOB_ONE_DATA => ${JOB_ONE_DATA}"
