name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # prerequisite job (use "needs" on all jobs to use the output)
  sha_generator_job:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha_gen.outputs.short_sha }}
    steps:
    - uses: actions/checkout@v2
    - id: sha_gen
      name: Generate a short SHA
      run: |
        export SHORT_SHA=${GITHUB_SHA::8}
        # OR: export SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)
        echo "::set-output name=short_sha::${SHORT_SHA}"

  main_job:
    runs-on: ubuntu-latest
    # this job must depend on the other!
    needs: sha_generator_job
    env:
      # sets the env var for all steps:
      SHORT_SHA: ${{ needs.sha_generator_job.outputs.short_sha }}
    steps:
    - uses: actions/checkout@v2
    # Now you can use it everywhere
    - name: Use short sha in jobs
      run: |
        echo "Short SHA calculated from job_one is: ${SHORT_SHA}"
